# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Homeworks/cpupip8/cpupip8.cache/wt [current_project]
set_property parent.project_path E:/Homeworks/cpupip8/cpupip8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/coe/test.coe
add_files e:/Homeworks/cpupip8/Tcoe/output.coe
read_verilog -library xil_defaultlib E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/seg7x16.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Homeworks/cpupip8/cpupip8.srcs/constrs_1/new/cpupip8.xdc
set_property used_in_implementation false [get_files E:/Homeworks/cpupip8/cpupip8.srcs/constrs_1/new/cpupip8.xdc]


synth_design -top seg7x16 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef seg7x16.dcp

catch { report_utilization -file seg7x16_utilization_synth.rpt -pb seg7x16_utilization_synth.pb }
