# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Homeworks/cpupip8/cpupip8.cache/wt [current_project]
set_property parent.project_path E:/Homeworks/cpupip8/cpupip8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files e:/Homeworks/cpupip8/cpupip8.srcs/sources_1/coe/test.coe
add_files -quiet E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/ip/imem/imem.dcp]
add_files -quiet e:/Homeworks/cpupip8/cpupip8.srcs/sources_1/ip/dmem1_1/dmem1.dcp
set_property used_in_implementation false [get_files e:/Homeworks/cpupip8/cpupip8.srcs/sources_1/ip/dmem1_1/dmem1.dcp]
read_verilog -library xil_defaultlib {
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/PCreg.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/def.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/regfile.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/NPCmaker.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/MEM_WB.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/IF_ID.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/ID_EX.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/EX_MEM.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/BJudge.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/ALU.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/IMEM.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/DMEM.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/cpu.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/sccomp_dataflow.v
  E:/Homeworks/cpupip8/cpupip8.srcs/sources_1/new/seg7x16.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Homeworks/cpupip8/cpupip8.srcs/constrs_1/new/cpupip8.xdc
set_property used_in_implementation false [get_files E:/Homeworks/cpupip8/cpupip8.srcs/constrs_1/new/cpupip8.xdc]


synth_design -top seg7x16 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef seg7x16.dcp

catch { report_utilization -file seg7x16_utilization_synth.rpt -pb seg7x16_utilization_synth.pb }
